import { useState, useMemo } from 'react';
import StatusBadge from './StatusBadge.jsx';

const CITY_META = {
  mumbai: {
    label: 'Mumbai',
    country: 'India 🇮🇳',
    subtitle: 'South Mumbai & Worli Supertall Cluster',
    tag: 'VERTICAL PILOT',
    color: '#38bdf8',
  },
  bengaluru: {
    label: 'Bengaluru',
    country: 'India 🇮🇳',
    subtitle: 'Tech Corridor & Metro Alignment',
    tag: 'TECH & STRATA',
    color: '#34d399',
  },
  singapore: {
    label: 'Singapore',
    country: 'Singapore 🇸🇬',
    subtitle: 'Marina Bay Strata & Caverns',
    tag: 'STRATA & CAVERNS',
    color: '#a78bfa',
  },
  netherlands: {
    label: 'Rotterdam',
    country: 'Netherlands 🇳🇱',
    subtitle: 'Wilhelminapier Maritime Strata',
    tag: 'EU 3D BENCHMARK',
    color: '#f59e0b',
  },
};

// ULPINCard — displays the prototype 3D identifier with copy button
function ULPINCard({ building }) {
  const [copied, setCopied] = useState(false);
  const copy = () => {
    navigator.clipboard.writeText(building.prototype_3d_id).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <div className="card ulpin-card">
      <div className="card-head">
        <h3>Prototype 3D Identifier</h3>
        <span className="badge badge-draft" style={{ fontSize: '10px' }}>NOT OFFICIAL ULPIN</span>
      </div>
      <div className="ulpin-display">
        <span className="mono ulpin-code">{building.prototype_3d_id}</span>
        <button
          className={`copy-btn ${copied ? 'copied' : ''}`}
          onClick={copy}
          title="Copy identifier"
          aria-label="Copy prototype identifier"
        >
          {copied
            ? <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>
            : <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
          }
        </button>
      </div>
      <div className="ulpin-disclaimer">
        This is a prototype spatial identifier generated by the 3D ULPIN engine.
        It is <strong>not</strong> an official Indian ULPIN/Bhu-Aadhaar number.
      </div>
    </div>
  );
}

// ProvenanceCard — source, CRS, confidence, acquisition date
function ProvenanceCard({ building }) {
  const p = building.provenance || {};
  const rows = [
    { label: 'Source Dataset',    value: p.source_dataset || 'OpenStreetMap / Cadastre GIS' },
    { label: 'CRS',               value: p.crs || 'EPSG:4979 (WGS84 3D)' },
    { label: 'Acquired',          value: p.acquired_at || '2024-11' },
    { label: 'Processing Version',value: p.processing_version || '0.1.0' },
    { label: 'Operator/Agent',    value: p.operator || 'PROTOTYPE-PIPELINE' },
    { label: 'Transformations',   value: p.transformations?.join(' → ') || 'WGS84→Local' },
    { label: 'Confidence',        value: <StatusBadge status={building.confidence || 'DERIVED_HIGH'} /> },
    { label: 'Data Label',        value: <StatusBadge status={building.data_label || 'DERIVED'} /> },
  ];
  return (
    <div className="card">
      <h3 className="card-head-title">Provenance</h3>
      <table className="prov-table">
        <tbody>
          {rows.map(r => (
            <tr key={r.label}>
              <td className="prov-label">{r.label}</td>
              <td className="prov-value">{r.value}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ValidationReport — checklist of validation items
function ValidationReport({ building }) {
  const checks = building.validation_checks ?? [];
  const iconMap = {
    VALID:   <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--green)" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>,
    REVIEW:  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--amber)" strokeWidth="2.5"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>,
    INVALID: <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--red)"   strokeWidth="2.5"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg>,
  };
  return (
    <div className="card">
      <h3 className="card-head-title">Validation Report</h3>
      <div className="check-list">
        {checks.map(c => (
          <div key={c.id} className={`check-item check-item--${(c.status || 'valid').toLowerCase()}`}>
            <span className="check-icon">{iconMap[c.status] || iconMap.VALID}</span>
            <span className="check-label">{c.label}</span>
            <StatusBadge status={c.status} />
          </div>
        ))}
      </div>
    </div>
  );
}

// FloorUnitList — list of floors for selected building
function FloorUnitList({ building, explodedFloor, onFloorClick }) {
  const floors = [...(building.floors ?? [])].sort((a, b) => b.level_index - a.level_index);
  return (
    <div className="card">
      <h3 className="card-head-title">Floors & Units ({floors.length})</h3>
      <div className="floor-list">
        {floors.map(f => (
          <button
            key={f.floor_id}
            className={`floor-item ${explodedFloor === f.floor_id ? 'floor-item--active' : ''}`}
            onClick={() => onFloorClick(f.floor_id === explodedFloor ? null : f.floor_id)}
          >
            <div className="floor-level">
              {f.level_index >= 0 ? `L${f.level_index}` : `B${Math.abs(f.level_index)}`}
            </div>
            <div className="floor-details">
              <div className="floor-label">{f.label}</div>
              <div className="floor-z mono" style={{ fontSize: '10px', color: 'var(--text-dim)' }}>
                z {f.z_min.toFixed(1)} — {f.z_max.toFixed(1)} m
              </div>
            </div>
            <StatusBadge status={f.status} />
          </button>
        ))}
      </div>
    </div>
  );
}

// BuildingInfoCard — main summary card
function BuildingInfoCard({ building }) {
  const infoRows = [
    { label: 'Building ID',  value: <span className="mono" style={{ fontSize: '11px' }}>{building.building_id}</span> },
    { label: 'Height',       value: `${Math.abs(building.height || 0).toFixed(1)} m` },
    { label: 'Floors',       value: building.floor_count },
    { label: 'Ground Elev.', value: `${building.ground_elevation || 0} m` },
    { label: 'Roof Elev.',   value: `${building.roof_elevation || 0} m` },
    { label: 'Source',       value: building.source || 'OSM / GIS' },
  ];
  return (
    <div className="card">
      <div className="card-head">
        <div>
          <div className="building-name">{building.name}</div>
          <div style={{ fontSize: '11px', color: 'var(--text-dim)', marginTop: '2px' }}>{building.city?.toUpperCase()}</div>
        </div>
        <StatusBadge status={building.validation_status || 'VALID'} dot />
      </div>
      {building.is_underground && (
        <div className="underground-badge">
          <span>⊗</span> Underground Infrastructure Volume
        </div>
      )}
      <table className="info-table">
        <tbody>
          {infoRows.map(r => (
            <tr key={r.label}>
              <td className="prov-label">{r.label}</td>
              <td className="prov-value">{r.value}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// DetailPanel — right sidebar, main container
export default function DetailPanel({
  city,
  buildings = [],
  building,
  onSelectBuilding,
  explodedFloor,
  onFloorClick,
  onClose,
  onEnterInterior,
  isCollapsed = false,
  onToggleCollapse,
}) {
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType]   = useState('all'); // 'all' | 'supertall' | 'underground'

  // Filtered building list for the city (Always called unconditionally at top)
  const filteredBuildings = useMemo(() => {
    if (!city || !buildings) return [];
    return buildings.filter(b => {
      const q = searchQuery.trim().toLowerCase();
      const matchesSearch = !q ||
        b.name?.toLowerCase().includes(q) ||
        b.building_id?.toLowerCase().includes(q) ||
        b.prototype_3d_id?.toLowerCase().includes(q);

      if (!matchesSearch) return false;

      if (filterType === 'supertall') {
        return (b.height || 0) >= 150;
      }
      if (filterType === 'underground') {
        return Boolean(b.is_underground);
      }
      return true;
    });
  }, [city, buildings, searchQuery, filterType]);

  // If not currently in a city (orbit mode), sidebar is completely removed
  if (!city) return null;

  const cityInfo = CITY_META[city] || {
    label: city,
    country: '',
    subtitle: 'Pilot Cadastre',
    tag: '3D PILOT',
    color: '#38bdf8',
  };

  // If collapsed by the user, show floating restore handle
  if (isCollapsed) {
    return (
      <button
        onClick={onToggleCollapse}
        className="sidebar-collapsed-pill"
        title="Open City Buildings List"
        aria-label="Expand City Buildings List"
      >
        <span style={{ fontSize: 13 }}>🏢</span>
        <span>Buildings ({buildings.length})</span>
        <span style={{ fontSize: 10, opacity: 0.6 }}>◀</span>
      </button>
    );
  }

  return (
    <aside className="detail-panel glass" id="detail-panel" aria-label="City Cadastre Panel">
      {/* ── Top Bar / Header ────────────────────────────────────────── */}
      <div className="panel-header-strip">
        {building ? (
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
            <button
              onClick={onClose}
              className="btn-back-list"
              title="Return to City Buildings List"
            >
              <span style={{ fontSize: 13 }}>←</span>
              <span>All Buildings ({buildings.length})</span>
            </button>

            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
              {onToggleCollapse && (
                <button
                  onClick={onToggleCollapse}
                  className="btn-header-action"
                  title="Collapse Sidebar"
                >
                  ▶
                </button>
              )}
              <button
                onClick={onClose}
                className="btn-header-action"
                title="Deselect Building"
              >
                ✕
              </button>
            </div>
          </div>
        ) : (
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{
                width: 8, height: 8, borderRadius: '50%',
                background: cityInfo.color,
                boxShadow: `0 0 8px ${cityInfo.color}`,
              }} />
              <div>
                <div style={{
                  fontFamily: "'Space Grotesk', sans-serif",
                  fontWeight: 700, fontSize: 13, letterSpacing: '0.4px',
                  color: '#ffffff', textTransform: 'uppercase',
                }}>
                  {cityInfo.label} CADASTRE
                </div>
                <div style={{ fontSize: 10, color: 'rgba(255, 255, 255, 0.45)' }}>
                  {cityInfo.country} • {buildings.length} 3D Assets
                </div>
              </div>
            </div>

            {onToggleCollapse && (
              <button
                onClick={onToggleCollapse}
                className="btn-header-action"
                title="Collapse Sidebar"
              >
                ▶
              </button>
            )}
          </div>
        )}
      </div>

      {/* ── Scrollable Body Area ────────────────────────────────────── */}
      <div className="detail-scroll scroll-area">
        {building ? (
          /* ── INSPECTION VIEW: SELECTED BUILDING ── */
          <div className="detail-cards anim-slide-right">
            {/* Quick Action: Walk Inside */}
            {onEnterInterior && (
              <button
                onClick={onEnterInterior}
                className="btn-walk-inside-cta"
                title="Walk inside the building lobby & elevator core"
              >
                <span>🚪</span>
                <span>Walk Inside Corridor & Floors</span>
                <span className="badge-floor-count">{building.floor_count}F</span>
              </button>
            )}

            <BuildingInfoCard building={building} />
            {building.prototype_3d_id && <ULPINCard building={building} />}
            <FloorUnitList building={building} explodedFloor={explodedFloor} onFloorClick={onFloorClick} />
            <ValidationReport building={building} />
            {building.provenance && <ProvenanceCard building={building} />}
          </div>
        ) : (
          /* ── BROWSER VIEW: ALL BUILDINGS IN CITY ── */
          <div className="city-buildings-browser">
            {/* Search Input */}
            <div className="building-search-box">
              <span style={{ fontSize: 12, opacity: 0.5 }}>🔍</span>
              <input
                type="text"
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
                placeholder={`Search ${buildings.length} buildings or IDs...`}
                className="building-search-input"
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery('')}
                  style={{ background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', fontSize: 11 }}
                >
                  ✕
                </button>
              )}
            </div>

            {/* Category Filter Chips */}
            <div className="filter-chips-row">
              <button
                className={`filter-chip ${filterType === 'all' ? 'active' : ''}`}
                onClick={() => setFilterType('all')}
              >
                All ({buildings.length})
              </button>
              <button
                className={`filter-chip ${filterType === 'supertall' ? 'active' : ''}`}
                onClick={() => setFilterType('supertall')}
              >
                Supertall (&gt;150m)
              </button>
              <button
                className={`filter-chip ${filterType === 'underground' ? 'active' : ''}`}
                onClick={() => setFilterType('underground')}
              >
                Underground
              </button>
            </div>

            <div className="building-list-hint">
              Click any building to inspect & fly camera, or click directly on 3D map:
            </div>

            {/* List of Building Cards */}
            <div className="building-cards-list">
              {filteredBuildings.length === 0 ? (
                <div className="no-buildings-found">
                  No buildings match "{searchQuery}"
                </div>
              ) : (
                filteredBuildings.map(b => {
                  const isSupertall = (b.height || 0) >= 200;
                  const isUnderground = Boolean(b.is_underground);
                  return (
                    <div
                      key={b.building_id}
                      onClick={() => onSelectBuilding?.(b.building_id, b)}
                      className="building-card-item"
                    >
                      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 6 }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 7, flex: 1, minWidth: 0 }}>
                          <span style={{ fontSize: 14 }}>
                            {isUnderground ? '🚇' : isSupertall ? '🏙' : '🏢'}
                          </span>
                          <div style={{ fontWeight: 600, fontSize: 12, color: '#f1f5f9', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                            {b.name}
                          </div>
                        </div>
                        <StatusBadge status={b.validation_status || 'VALID'} dot />
                      </div>

                      <div className="building-card-meta">
                        <span>{Math.abs(b.height || 0).toFixed(1)}m</span>
                        <span>•</span>
                        <span>{b.floor_count} Floors</span>
                        {isUnderground && (
                          <>
                            <span>•</span>
                            <span style={{ color: '#c084fc' }}>Subterranean</span>
                          </>
                        )}
                      </div>

                      <div className="building-card-ulpin-row">
                        <span className="mono" style={{ fontSize: 10, color: 'rgba(255,255,255,0.4)' }}>
                          {b.prototype_3d_id ? `${b.prototype_3d_id.slice(0, 18)}…` : b.building_id}
                        </span>
                        <span className="building-card-inspect-arrow">Inspect →</span>
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>
        )}
      </div>

      <style>{detailStyles}</style>
    </aside>
  );
}

const detailStyles = `
  .detail-panel {
    position: fixed;
    top: 52px; right: 0; bottom: 0;
    width: var(--panel-w, 340px);
    display: flex; flex-direction: column;
    border-radius: 0; border-right: none; border-top: none; border-bottom: none;
    border-left: 1px solid rgba(255, 255, 255, 0.10);
    background: rgba(5, 7, 12, 0.88);
    backdrop-filter: blur(20px);
    z-index: 85;
    overflow: hidden;
    box-shadow: -10px 0 30px rgba(0, 0, 0, 0.6);
    user-select: none;
  }

  .panel-header-strip {
    padding: 10px 14px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.08);
    background: rgba(0, 0, 0, 0.35);
    display: flex; align-items: center;
    flex-shrink: 0;
  }

  .btn-back-list {
    display: flex; align-items: center; gap: 6px;
    background: rgba(255, 255, 255, 0.06);
    border: 1px solid rgba(255, 255, 255, 0.14);
    border-radius: 999px;
    padding: 4px 12px;
    color: #38bdf8;
    font-size: 11px; font-weight: 600;
    font-family: inherit;
    cursor: pointer;
    transition: all 0.15s;
  }
  .btn-back-list:hover {
    background: rgba(56, 189, 248, 0.15);
    border-color: #38bdf8;
  }

  .btn-header-action {
    background: none; border: none;
    color: rgba(255, 255, 255, 0.6);
    cursor: pointer; padding: 4px 6px;
    font-size: 12px; border-radius: 4px;
    display: flex; align-items: center; justify-content: center;
    transition: color 0.15s;
  }
  .btn-header-action:hover {
    color: #ffffff;
    background: rgba(255, 255, 255, 0.08);
  }

  .detail-scroll {
    flex: 1; overflow-y: auto; padding: 12px;
    display: flex; flex-direction: column; gap: 12px;
  }

  /* Browser View */
  .city-buildings-browser {
    display: flex; flex-direction: column; gap: 10px;
  }

  .building-search-box {
    display: flex; align-items: center; gap: 8px;
    background: rgba(255, 255, 255, 0.04);
    border: 1px solid rgba(255, 255, 255, 0.10);
    border-radius: 8px; padding: 7px 10px;
  }
  .building-search-input {
    flex: 1; background: transparent; border: none;
    outline: none; color: #fff;
    font-family: inherit; font-size: 12px;
  }
  .building-search-input::placeholder {
    color: rgba(255, 255, 255, 0.35);
  }

  .filter-chips-row {
    display: flex; align-items: center; gap: 6px;
    overflow-x: auto; padding-bottom: 2px;
  }
  .filter-chip {
    background: rgba(255, 255, 255, 0.04);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 999px;
    padding: 3px 10px;
    font-size: 10px; font-weight: 600;
    color: rgba(255, 255, 255, 0.6);
    cursor: pointer; white-space: nowrap;
    transition: all 0.15s;
  }
  .filter-chip.active {
    background: rgba(56, 189, 248, 0.15);
    border-color: #38bdf8;
    color: #38bdf8;
  }

  .building-list-hint {
    font-size: 10px; color: rgba(255, 255, 255, 0.4);
    line-height: 1.4; padding: 0 2px;
  }

  .building-cards-list {
    display: flex; flex-direction: column; gap: 6px;
  }

  .building-card-item {
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.07);
    border-radius: 8px;
    padding: 9px 10px;
    cursor: pointer;
    transition: all 0.15s cubic-bezier(0.16, 1, 0.3, 1);
    display: flex; flex-direction: column; gap: 4px;
  }
  .building-card-item:hover {
    background: rgba(56, 189, 248, 0.07);
    border-color: rgba(56, 189, 248, 0.35);
    transform: translateX(-2px);
  }
  .building-card-meta {
    display: flex; align-items: center; gap: 6px;
    font-size: 10px; color: rgba(255, 255, 255, 0.5);
  }
  .building-card-ulpin-row {
    display: flex; align-items: center; justify-content: space-between;
    margin-top: 2px;
  }
  .building-card-inspect-arrow {
    font-size: 10px; font-weight: 600; color: #38bdf8;
    opacity: 0; transform: translateX(-4px);
    transition: all 0.15s;
  }
  .building-card-item:hover .building-card-inspect-arrow {
    opacity: 1; transform: translateX(0);
  }

  .no-buildings-found {
    padding: 24px; text-align: center;
    font-size: 12px; color: rgba(255, 255, 255, 0.4);
  }

  /* Inspection View */
  .detail-cards { display: flex; flex-direction: column; gap: 12px; }

  .btn-walk-inside-cta {
    display: flex; align-items: center; justify-content: space-between;
    padding: 10px 14px;
    border-radius: 10px;
    background: linear-gradient(135deg, rgba(6, 182, 212, 0.2) 0%, rgba(59, 130, 246, 0.2) 100%);
    border: 1px solid rgba(6, 182, 212, 0.5);
    color: #ffffff;
    font-family: inherit; font-size: 12px; font-weight: 600;
    cursor: pointer;
    box-shadow: 0 4px 16px rgba(6, 182, 212, 0.18);
    transition: all 0.15s;
  }
  .btn-walk-inside-cta:hover {
    background: linear-gradient(135deg, rgba(6, 182, 212, 0.3) 0%, rgba(59, 130, 246, 0.3) 100%);
    border-color: #38bdf8;
    transform: translateY(-1px);
  }
  .badge-floor-count {
    background: rgba(6, 182, 212, 0.3);
    border: 1px solid rgba(6, 182, 212, 0.6);
    border-radius: 4px; padding: 2px 6px;
    font-size: 10px; font-weight: 700; color: #38bdf8;
  }

  /* Collapsed floating tab */
  .sidebar-collapsed-pill {
    position: fixed;
    top: 66px; right: 20px; z-index: 85;
    display: flex; align-items: center; gap: 8px;
    padding: 7px 14px;
    background: rgba(9, 11, 16, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.15);
    border-radius: 999px;
    color: #ffffff;
    font-family: inherit; font-size: 11px; font-weight: 600;
    cursor: pointer;
    backdrop-filter: blur(12px);
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.6);
    transition: all 0.15s;
  }
  .sidebar-collapsed-pill:hover {
    border-color: #38bdf8;
    color: #38bdf8;
    transform: scale(1.02);
  }

  /* Cards */
  .card {
    background: rgba(255,255,255,0.03);
    border: 1px solid rgba(255,255,255,0.08);
    border-radius: var(--r-md);
    padding: var(--gap-md);
  }
  .card-head {
    display: flex; align-items: flex-start; justify-content: space-between;
    gap: var(--gap-sm); margin-bottom: var(--gap-md);
  }
  .card-head-title { margin-bottom: var(--gap-sm); }
  .building-name { font-size: 15px; font-weight: 600; color: var(--text-primary); }

  /* ULPIN */
  .ulpin-card { border-color: rgba(0,212,255,0.2); background: rgba(0,212,255,0.04); }
  .ulpin-display {
    display: flex; align-items: center; gap: 8px;
    background: rgba(0,0,0,0.3); border: 1px solid var(--border);
    border-radius: var(--r-sm); padding: 10px 12px;
    margin-bottom: 8px;
  }
  .ulpin-code { flex: 1; word-break: break-all; font-size: 12px; }
  .ulpin-disclaimer { font-size: 11px; color: var(--text-dim); line-height: 1.5; }

  /* Tables */
  .prov-table, .info-table { width: 100%; border-collapse: collapse; }
  .prov-table tr, .info-table tr { border-bottom: 1px solid rgba(255,255,255,0.04); }
  .prov-table tr:last-child, .info-table tr:last-child { border-bottom: none; }
  .prov-label { font-size: 11px; color: var(--text-dim); padding: 5px 0; width: 45%; vertical-align: top; }
  .prov-value { font-size: 12px; color: var(--text-primary); padding: 5px 0; text-align: right; }

  /* Checks */
  .check-list { display: flex; flex-direction: column; gap: 4px; }
  .check-item {
    display: flex; align-items: center; gap: 8px;
    padding: 6px 8px; border-radius: var(--r-sm);
    border: 1px solid transparent;
    transition: background var(--t-fast);
  }
  .check-item--valid   { background: rgba(16,217,126,0.04); }
  .check-item--review  { background: rgba(245,158,11,0.04); }
  .check-item--invalid { background: rgba(239,68,68,0.04); }
  .check-icon { flex-shrink: 0; display: flex; }
  .check-label { flex: 1; font-size: 12px; color: var(--text-primary); }

  /* Floors */
  .floor-list { display: flex; flex-direction: column; gap: 4px; }
  .floor-item {
    display: flex; align-items: center; gap: 10px;
    width: 100%; text-align: left;
    background: rgba(255,255,255,0.02);
    border: 1px solid var(--border);
    border-radius: var(--r-sm);
    padding: 8px 10px; cursor: pointer;
    transition: background var(--t-fast), border-color var(--t-fast);
  }
  .floor-item:hover { background: var(--cyan-dim); border-color: var(--cyan); }
  .floor-item--active { background: var(--cyan-dim); border-color: var(--cyan); box-shadow: var(--cyan-glow); }
  .floor-level {
    font-family: var(--font-mono); font-size: 11px; font-weight: 700;
    color: var(--cyan); width: 22px; text-align: center; flex-shrink: 0;
  }
  .floor-details { flex: 1; }
  .floor-label { font-size: 12px; color: var(--text-primary); font-weight: 500; }

  /* Underground badge */
  .underground-badge {
    display: flex; align-items: center; gap: 6px;
    background: rgba(168,85,247,0.1); border: 1px solid rgba(168,85,247,0.25);
    border-radius: var(--r-sm); padding: 6px 10px;
    font-size: 11px; color: var(--synthetic); margin-bottom: var(--gap-sm);
  }
`;
