"""
LiDAR Point Cloud Reader — LAS / LAZ → PointCloudData (numpy structured array)
Conforms to docs/implementation_plan.md Phase 1.5.

Uses 'laspy' (pure Python LAS 1.0-1.4 / 2.0 reader) as the primary backend.
Falls back to a minimal numpy-only binary reader for synthetic LAS files
generated by sensor_sim.py (to avoid a mandatory laspy install in CI).

Every read operation attaches a ProvenanceRecord.
"""
from __future__ import annotations

import os
import struct
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional, Tuple, Dict, Any

import numpy as np

from backend.ingestion.provenance import ProvenanceRecord, LedgerStore


# ---------------------------------------------------------------------------
# PointCloudData — canonical output from any LiDAR reader path
# ---------------------------------------------------------------------------
@dataclass
class PointCloudData:
    """
    Standardised container for a 3D point cloud consumed by the pipeline.

    Attributes
    ----------
    points      : np.ndarray, shape (N, 3) — X, Y, Z in CRS units
    intensities : np.ndarray, shape (N,)   — reflectivity / return intensity
    provenance  : str                      — VALID_PROVENANCE_TAGS member
    crs         : str                      — CRS of the XY coordinates
    point_count : int                      — cached N
    """
    points: np.ndarray          # shape (N, 3) float64
    intensities: np.ndarray     # shape (N,)   uint8 or float32
    provenance: str = "SYNTHETIC"
    crs: str = "EPSG:4326"

    @property
    def point_count(self) -> int:
        return int(self.points.shape[0])

    def bounding_box(self) -> Tuple[np.ndarray, np.ndarray]:
        """Returns (min_xyz, max_xyz) each shape (3,)."""
        return self.points.min(axis=0), self.points.max(axis=0)


# ---------------------------------------------------------------------------
# LidarReader
# ---------------------------------------------------------------------------
class LidarReader:
    """
    Reads LAS (1.0–1.4) and LAZ files, returning a PointCloudData.

    Dependency: `pip install laspy[lazrs]`
    Falls back gracefully to a minimal raw-binary parser for uncompressed LAS
    produced by SensorSimulator (which writes a compliant LAS 1.2 header).
    """

    def __init__(self, ledger: Optional[LedgerStore] = None) -> None:
        self.ledger = ledger

    def read(
        self,
        path: str,
        source_id: str,
        data_provenance: str,
        license: str = "UNKNOWN",
        notes: str = "",
        crs: str = "EPSG:4326",
        accuracy_sigma_m: Optional[float] = None,
    ) -> Tuple[PointCloudData, ProvenanceRecord]:
        """
        Read a .las or .laz file into PointCloudData.

        Parameters
        ----------
        path              : absolute or relative path to the LAS/LAZ file
        source_id         : unique identifier for the provenance ledger
        data_provenance   : 'REAL', 'SYNTHETIC', 'REAL-FOREIGN', etc.
        license           : SPDX licence string
        notes             : free-text note (flight date, sensor, altitude, etc.)
        crs               : coordinate reference system of XY columns
        accuracy_sigma_m  : 1-sigma positional accuracy; None if unknown

        Returns
        -------
        (PointCloudData, ProvenanceRecord)
        """
        if not os.path.exists(path):
            raise FileNotFoundError(f"LAS/LAZ file not found: {path}")

        ext = os.path.splitext(path)[1].lower()
        if ext not in (".las", ".laz"):
            raise ValueError(f"Unsupported extension '{ext}'. Expected .las or .laz")

        # --- primary reader: laspy -------------------------------------------
        try:
            import laspy
            pc_data = self._read_laspy(path, data_provenance, crs)
        except ImportError:
            if ext == ".laz":
                raise ImportError(
                    "laspy[lazrs] is required to read .laz files. "
                    "Install with: pip install laspy[lazrs]"
                )
            # Minimal fallback for synthetic, uncompressed LAS
            pc_data = self._read_raw_las(path, data_provenance, crs)

        # Estimate resolution from point spacing (average NN distance in XY)
        resolution_m = _estimate_resolution(pc_data.points)

        record = ProvenanceRecord(
            source_id=source_id,
            file_path=os.path.abspath(path),
            data_provenance=data_provenance,
            crs=crs,
            datum="WGS84",
            resolution_m=resolution_m,
            accuracy_sigma_m=accuracy_sigma_m,
            license=license,
            download_ts=_now_iso(),
            notes=notes,
        )

        if self.ledger:
            self.ledger.log(record)

        return pc_data, record

    # ------------------------------------------------------------------
    # Backend: laspy (preferred)
    # ------------------------------------------------------------------
    @staticmethod
    def _read_laspy(
        path: str, data_provenance: str, crs: str
    ) -> PointCloudData:
        import laspy  # noqa: F401

        las = laspy.read(path)
        x = np.array(las.x, dtype=np.float64)
        y = np.array(las.y, dtype=np.float64)
        z = np.array(las.z, dtype=np.float64)

        points = np.column_stack([x, y, z])

        try:
            intensities = np.array(las.intensity, dtype=np.float32)
        except Exception:
            intensities = np.zeros(len(x), dtype=np.float32)

        return PointCloudData(
            points=points,
            intensities=intensities,
            provenance=data_provenance,
            crs=crs,
        )

    # ------------------------------------------------------------------
    # Backend: minimal raw LAS parser (fallback for CI without laspy)
    # ------------------------------------------------------------------
    @staticmethod
    def _read_raw_las(
        path: str, data_provenance: str, crs: str
    ) -> PointCloudData:
        """
        Reads a LAS 1.0–1.2 file without laspy.
        Only supports Point Data Format 0 and 1 (the formats sensor_sim writes).
        """
        with open(path, "rb") as fh:
            header = fh.read(227)  # LAS 1.0-1.2 header is 227 bytes minimum
            if header[:4] != b"LASF":
                raise ValueError("Not a valid LAS file (missing 'LASF' signature)")

            # Byte offsets per LAS 1.2 spec
            point_data_offset = struct.unpack_from("<I", header, 96)[0]
            point_data_format = struct.unpack_from("<B", header, 104)[0]
            point_record_len  = struct.unpack_from("<H", header, 105)[0]
            num_points        = struct.unpack_from("<I", header, 107)[0]
            x_scale = struct.unpack_from("<d", header, 131)[0]
            y_scale = struct.unpack_from("<d", header, 139)[0]
            z_scale = struct.unpack_from("<d", header, 147)[0]
            x_off   = struct.unpack_from("<d", header, 155)[0]
            y_off   = struct.unpack_from("<d", header, 163)[0]
            z_off   = struct.unpack_from("<d", header, 171)[0]

            fh.seek(point_data_offset)
            raw = fh.read(num_points * point_record_len)

        # Parse X, Y, Z (int32 each, first 12 bytes of every point record)
        stride = point_record_len
        xs = np.frombuffer(raw, dtype="<i4", count=num_points, offset=0)[::stride // 4]
        ys = np.frombuffer(raw, dtype="<i4", count=num_points, offset=4)[::stride // 4]
        zs = np.frombuffer(raw, dtype="<i4", count=num_points, offset=8)[::stride // 4]

        # Recover real-world float coordinates
        x_f = xs.astype(np.float64) * x_scale + x_off
        y_f = ys.astype(np.float64) * y_scale + y_off
        z_f = zs.astype(np.float64) * z_scale + z_off

        points = np.column_stack([x_f, y_f, z_f])

        # Intensity at bytes 14-15 (uint16) in format 0/1
        intensities = np.zeros(num_points, dtype=np.float32)
        try:
            raw_bytes = np.frombuffer(raw, dtype=np.uint8).reshape(num_points, stride)
            intensities = raw_bytes[:, 12].astype(np.float32)
        except Exception:
            pass

        return PointCloudData(
            points=points,
            intensities=intensities,
            provenance=data_provenance,
            crs=crs,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _estimate_resolution(points: np.ndarray) -> Optional[float]:
    """
    Estimates average point spacing in XY from a random 1,000-point sample.
    Returns None if fewer than 2 points.
    """
    if points.shape[0] < 2:
        return None
    sample_n = min(1000, points.shape[0])
    idx = np.random.choice(points.shape[0], size=sample_n, replace=False)
    xy = points[idx, :2]
    # Average distance between consecutive points in the sample
    diff = np.diff(xy, axis=0)
    dists = np.sqrt((diff ** 2).sum(axis=1))
    mean_spacing = float(np.median(dists))
    return round(mean_spacing, 4)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()
